### ISSUE TITLE
the labelmap.txt file is missing in your yolo model on kaggle

### ISSUE THREAD

**Issue by martinmmi** [tensorflow/tfhub.dev#151]
Hello, i tried to employ your yolo v5 model, but there are a mssing file, where the labels are named. 

What can i do? 

Somewhere i read, that the label files are included into the tensorflow lite models. (.tflite)

![image](https://github.com/tensorflow/tfhub.dev/assets/118231543/733c0f1c-ebd1-496c-9815-22bf62a06824)

My list from a other model is in the same file like the .tflite model an included something like this:

![image](https://github.com/tensorflow/tfhub.dev/assets/118231543/68c999e7-2af2-4df1-bca4-c26830c6e98e)

**Comment by WGierke** [comment]
Sorry for the late reply - [tfhub.dev](http://tfhub.dev/) has been converged with [Kaggle Models](https://kaggle.com/models). You can refer [here](https://www.kaggle.com/discussions/product-feedback/448425) for an update. Future inquiries will be handled by the Kaggle team on https://kaggle.com/models. Thank you!
