### ISSUE TITLE
Dataset used for pretraining and finetuning GTR model

### ISSUE THREAD

**Issue by ashokrajab** [tensorflow/tfhub.dev#155]
I'm trying to reproduce the results presented in **Large Dual Encoders Are Generalizable Retrievers** paper and perform some experiments.
So I'm in need of the dataset used for pretraining and finetuning GTR models.

**Comment by WGierke** [comment]
Sorry for the late reply - [tfhub.dev](http://tfhub.dev/) has been converged with [Kaggle Models](https://kaggle.com/models). You can refer [here](https://www.kaggle.com/discussions/product-feedback/448425) for an update. Future contributions will be handled by the Kaggle team on https://kaggle.com/models. Thank you!
