### ISSUE TITLE
Regarding replacing a Hub model

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tfhub.dev#32]
I am writing to know what's the best way to replace a model on TensorFlow Hub? Today, I noticed the [int8 EAST model](https://tfhub.dev/sayakpaul/lite-model/east-text-detector/int8/1) is a bit buggy and I worked on a fix today. I wish to replace the existing one now. What should be the course of action here?

**Comment by arnoegw** [comment]
To fix tfhub.dev/sayakpaul/lite-model/east-text-detector/int8<b>/1</b>, you can publish a new model version tfhub.dev/sayakpaul/lite-model/east-text-detector/int8<b>/2</b> (or whichever higher integer makes sense). Both versions will coexist (each with its own documentation), but users who browse to model version /1 will see a notice pointing out the newer version.

For an existing example, see https://tfhub.dev/google/lite-model/aiy/vision/classifier/plants_V1/1 and its updates to /2 and /3. In that example, the authors chose to put a Changelog into the documentation that grows with each version and explains what improvement each version has brought.

In documentation, you can use an unversioned link https://tfhub.dev/sayakpaul/lite-model/east-text-detector/int8 to send web browsers to the most recent model version. However, model handles uses in code must be versioned, to avoid unexpected changes of behavior and race conditions in distributed training.

**Comment by sayakpaul** [comment]
Thanks @arnoegw. Will proceed accordingly.
