### ISSUE TITLE
Adding a plant disease model

### ISSUE THREAD

**Issue by Rishit-dagli** [tensorflow/tfhub.dev#48]
I am planning on adding TensorFlow SavedModel and TFJS models for identifying plant diseases using the [plant_village](https://www.tensorflow.org/datasets/catalog/plant_village) dataset on top of MobileNet. My final set of experiments for the models can be found in [this repo](https://github.com/Rishit-dagli/Greenathon-Plant-AI). I did not find any such model or related model on TF Hub.

I request you to kindly review this, should I create a PR adding this model?

**Comment by MorganR** [comment]
Hello @Rishit-dagli, this sounds like it would be a great addition to TF Hub. A PR would be welcome.

I think our closest models currently are the Cassava disease models, but these are strictly for the Cassava plant: 

* https://tfhub.dev/google/cropnet/classifier/cassava_disease_V1/2
* https://tfhub.dev/google/cropnet/feature_vector/cassava_disease_V1/1
